aws-controllers-k8s/elasticache-controller

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
The repository does not contain templates for the pull requests and issues.
Added templates for pull requests and issues (similar to `community`, `code-generator` modules).
> templates for pull requests and issues

- .gitignore
- Makefile
- go.local.mod
During development, workspace directory setup looks like:
Example setup including ElastiCache service controller along with ACK packages:
```
aws-controllers-k8s
├── code-generator
├── community
├── elasticache-controller
└── runtime
```
To build service controller image against local changes in ```runtime``` module, create`elasticache-controller/go.local.mod` file with `replace`:
```
replace github.com/aws-controllers-k8s/runtime => ../runtime
```
Also support `make local-test` to run local unit tests using local `runtime` module.
Related PR in `community` module: https://github.com/aws-controllers-k8s/community/pull/682
* Added `elasticache-controller/go.local.mod`
* Added `elasticache-controller/go.local.sum` to `.gitignore`
* Added `make …
> Allow reference to local runtime module using local go mod file

- Makefile
Followup to PR #6 comment: https://github.com/aws-controllers-k8s/elasticache-controller/pull/6#discussion_r579296838
> to replace the 1.37.4 hard-coding above by looking in the go.mod file
Updated the `Makefile` to read the `aws-sdk-go` version dynamically.
> To generate mocks, determine aws-sdk-go version from go.mod file

- pkg/resource/replication_group/custom_update_api_test.go
- pkg/resource/replication_group/testdata/DecreaseReplicaCountOutput.json
- pkg/resource/replication_group/testdata/DescribeReplicationGroupsOutput.json
- pkg/testutil/util.go
This PR adds methods to create mock ElastiCache API output from json file.
This would help unit test scenarios by adding corresponding API response json from file.
> mock api output from json file for unit tests

- .github/workflows/unit-test-cover.yaml
- .gitignore
- Makefile
* Added option to generate coverage details during unit tests
* GitHub workflow to use `make test-cover` 
> option to generate coverage details during unit tests

- config/iam/KMS-policy-template.json
- config/iam/README.md
The KMS snapshot test will fail if the test IAM role does not have the proper permissions. Added some instructions to complement this page to ensure proper test setup: https://aws-controllers-k8s.github.io/community/dev-docs/testing/#iam-setup
> add instructions to attach additional IAM policies for test setup

- apis/v1alpha1/replication_group.go
- apis/v1alpha1/zz_generated.deepcopy.go
- config/crd/bases/elasticache.services.k8s.aws_replicationgroups.yaml
- generator.yaml
- go.mod
- go.sum
- pkg/resource/cache_parameter_group/sdk.go
- pkg/resource/cache_subnet_group/sdk.go
- pkg/resource/replication_group/sdk.go
- pkg/resource/snapshot/sdk.go
- Update AuthToken to use SecretKeyRef.
- Automatically generated, depends upon
- Runtime code changes.
Other PRs -
Codegen gen - https://github.com/aws-controllers-k8s/code-generator/pull/21
Runtime changes - https://github.com/aws-controllers-k8s/runtime/pull/5
New test payload.
```
apiVersion: elasticache.services.k8s.aws/v1alpha1
kind: ReplicationGroup
metadata:
name: testing
spec:
engine: redis
replicationGroupID: testing
replicationGroupDescription: Test replication group
cacheNodeType: cache.t3.micro
numNodeGroups: 2
replicasPerNodeGroup: 2
authToken:
name: test-secret
key: auth
transitEncryptionEnabled: true
cacheSubnetGroupName: default
````
Probably would require runtime PR to be merged before merging this.
By submitting this pull request, I confirm that my contribution is made …
> AuthToken - Use SecretRef

- pkg/resource/replication_group/manager_test_suite_test.go
- pkg/testutil/test_suite_runner.go
Declarative Unit test: https://github.com/aws-controllers-k8s/elasticache-controller/pull/14 needs enhancements to support additional resource manager apis.
* Declarative Unit tests for resource manager `Create`, `Update`, `Delete` apis.
* Support for mocking additional ElastiCache service API methods for replication group resource.
> Enhance declarative unit test framework to include additional resoure manager apis

- pkg/resource/replication_group/custom_update_api.go
- pkg/resource/replication_group/custom_update_api_test.go
- pkg/resource/replication_group/testdata/cache_clusters/read_many/rg_cmd_primary_cache_node.json
- pkg/resource/replication_group/testdata/replication_group/cr/rg_cmd_before_engine_version_upgrade.yaml
- pkg/resource/replication_group/testdata/replication_group/cr/rg_cmd_before_increase_replica.yaml
- pkg/resource/replication_group/testdata/replication_group/cr/rg_cmd_before_scale_up_desired.yaml
- pkg/resource/replication_group/testdata/replication_group/cr/rg_cmd_before_scale_up_latest.yaml
- pkg/resource/replication_group/testdata/replication_group/cr/rg_cmd_engine_upgrade_initiated.yaml
- pkg/resource/replication_group/testdata/replication_group/cr/rg_cmd_increase_replica_initiated.yaml
- pkg/resource/replication_group/testdata/replication_group/cr/rg_cmd_scale_up_initiated.yaml
- pkg/resource/replication_group/testdata/replication_group/cr/rg_cme_before_create.yaml
- pkg/resource/replication_group/testdata/replication_group/cr/rg_cme_create_initiated.yaml
- pkg/resource/replication_group/testdata/replication_group/cr/rg_cme_invalid_scale_out_attempted.yaml
- pkg/resource/replication_group/testdata/replication_group/cr/rg_cme_shard_mismatch.yaml
- pkg/resource/replication_group/testdata/replication_group/create/rg_cme_creating.json
- pkg/resource/replication_group/testdata/replication_group/update/rg_cmd_engine_upgrade_initiated.json
- pkg/resource/replication_group/testdata/replication_group/update/rg_cmd_increase_replica_initiated.json
- pkg/resource/replication_group/testdata/replication_group/update/rg_cmd_scale_up_initiated.json
- pkg/resource/replication_group/testdata/test_suite.yaml
- increase replication group code coverage (probably best to focus review on `test_suite.yaml` since there are many `testdata` files)
- small tweak to engineVersionsDiffer: removed the second argument as it was unused
> add replication group declarative tests, remove unused argument from engineVersionsDiffer

- generator.yaml
- pkg/resource/replication_group/custom_update_api.go
- pkg/resource/replication_group/custom_update_api_test.go
- pkg/resource/replication_group/manager_test.go
- pkg/resource/replication_group/post_set_output.go
- pkg/resource/replication_group/sdk.go
- pkg/resource/replication_group/testdata/replication_group/cr/rg_cmd_before_engine_version_upgrade_latest.yaml
- pkg/resource/replication_group/testdata/replication_group/cr/rg_cmd_before_increase_replica_latest.yaml
- pkg/resource/replication_group/testdata/replication_group/cr/rg_cmd_engine_upgrade_initiated.yaml
- pkg/resource/replication_group/testdata/test_suite.yaml
Related to https://github.com/aws-controllers-k8s/elasticache-controller/pull/22
To recap, in order to trigger the `Update` code, there needs to be a Spec difference between `desired` and `latest`. The generated `ReadOne` code often doesn't update `latest.Spec` with the latest observed state, since determining the latest observed state often requires some processing or additional API calls. There are many fields this applies to, but this PR starts with `ReplicasPerNodeGroup` and `EngineVersion`
> Update spec fields in ReadOne post_set_output hook

- test/e2e/conftest.py
- test/e2e/resources/replicationgroup_cmd_fromsnapshot.yaml
- test/e2e/resources/replicationgroup_input_coverage.yaml
- test/e2e/tests/test_replicationgroup.py
Address e2e test failures:
- `test_rg_input_coverage` was failing because the type of the `authToken` field has changed since the test was written
- `test_rg_auth_token` was failing because the controller does not have permissions to list secrets. For now, we are skipping this test. See issue https://github.com/aws-controllers-k8s/community/issues/745
- `test_rg_cmd_fromsnapshot` succeeds locally but failed in the last Prow run. This was likely due to a region mismatch (tests run in us-west-2, input yamls specify us-east-1 AZs)
> fix Prow e2e test run failures

- generator.yaml
- pkg/resource/replication_group/hooks.go
- pkg/resource/replication_group/post_set_output.go
- pkg/resource/replication_group/sdk.go
- pkg/resource/replication_group/testdata/replication_group/cr/rg_cmd_delete_initiated.yaml
- pkg/resource/replication_group/testdata/replication_group/read_one/rg_cmd_delete_initiated.json
- pkg/resource/replication_group/testdata/test_suite.yaml
- templates/hooks/sdk_delete_post_request.go.tpl
- templates/hooks/sdk_delete_pre_build_request.go.tpl
- test/e2e/tests/test_replicationgroup.py
Replication group delete takes some time to delete while `kubectl delete -f replication_group.yaml` removes the custom resource record from cluster.
This PR adds logic inside `sdk::sdkDelete()` to requeue reconcile while replication group is deleting.
> Delete replication group to wait for delete completion

- pkg/resource/user/delta_util.go
- pkg/resource/user/post_build_request.go
- test/e2e/tests/test_replicationgroup.py
- Change User code to be compatible with https://github.com/aws-controllers-k8s/runtime/pull/20
- Fix RG deletion test (pytest was complaining about a direct call to a fixture)
Local e2e test run:
```
============================================================================ test session starts =============================================================================
platform linux -- Python 3.8.10, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /elasticache-controller/tests/e2e
plugins: xdist-2.2.0, forked-1.3.0
[gw0] Python 3.8.10 (default, May  4 2021, 19:07:02)  -- [GCC 10.2.1 20201203]
[gw1] Python 3.8.10 (default, May  4 2021, 19:07:02)  -- [GCC 10.2.1 20201203]
[gw2] Python 3.8.10 (default, May  4 2021, 19:07:02)  -- [GCC 10.2.1 20201203]
[gw3] Python …
```
> address regression with User code, fix RG deletion test

- test/e2e/tests/test_user.py
- test/e2e/util.py
User tests were failing upon asserting the deletion (the logic I initially wrote was somewhat unsophisticated)
Ensure either 1) the User is deleting, or 2) the User has already been deleted (as opposed to waiting an arbitrary amount of time before assuming the User should be deleted)
> fix deletion assertions in user e2e tests

- apis/v1alpha1/ack-generate-metadata.yaml
- apis/v1alpha1/generator.yaml
- cmd/controller/main.go
- go.mod
- go.sum
- pkg/resource/cache_parameter_group/manager.go
- pkg/resource/cache_parameter_group/resource.go
- pkg/resource/cache_parameter_group/sdk.go
- pkg/resource/cache_subnet_group/manager.go
- pkg/resource/cache_subnet_group/resource.go
- pkg/resource/cache_subnet_group/sdk.go
- pkg/resource/replication_group/manager.go
- pkg/resource/replication_group/resource.go
- pkg/resource/replication_group/sdk.go
- pkg/resource/replication_group/testdata/test_suite.yaml
- pkg/resource/snapshot/manager.go
- pkg/resource/snapshot/resource.go
- pkg/resource/snapshot/sdk.go
- pkg/resource/user/manager.go
- pkg/resource/user/resource.go
- pkg/resource/user/sdk.go
- pkg/resource/user_group/manager.go
- pkg/resource/user_group/resource.go
- pkg/resource/user_group/sdk.go
- pkg/testutil/test_suite_runner.go
- templates/hooks/sdk_delete_post_request.go.tpl
- templates/hooks/sdk_delete_pre_build_request.go.tpl
Please check if the resulting `sdkDelete` is as intended.
> regenerate code, fix replication group delete templates, upgrade to runtime 0.6.0

- apis/v1alpha1/ack-generate-metadata.yaml
- apis/v1alpha1/cache_parameter_group.go
- apis/v1alpha1/cache_subnet_group.go
- apis/v1alpha1/generator.yaml
- apis/v1alpha1/replication_group.go
- apis/v1alpha1/snapshot.go
- apis/v1alpha1/user.go
- apis/v1alpha1/user_group.go
- apis/v1alpha1/zz_generated.deepcopy.go
- config/crd/bases/elasticache.services.k8s.aws_cacheparametergroups.yaml
- config/crd/bases/elasticache.services.k8s.aws_cachesubnetgroups.yaml
- config/crd/bases/elasticache.services.k8s.aws_replicationgroups.yaml
- config/crd/bases/elasticache.services.k8s.aws_snapshots.yaml
- config/crd/bases/elasticache.services.k8s.aws_usergroups.yaml
- config/crd/bases/elasticache.services.k8s.aws_users.yaml
- generator.yaml
- go.mod
- go.sum
- pkg/resource/cache_parameter_group/sdk.go
- pkg/resource/cache_subnet_group/sdk.go
- pkg/resource/replication_group/custom_update_api.go
- pkg/resource/replication_group/delta.go
- pkg/resource/replication_group/sdk.go
- pkg/resource/snapshot/sdk.go
- pkg/resource/user/sdk.go
- pkg/resource/user_group/sdk.go
- test/e2e/resources/replicationgroup_cmd_fromsnapshot.yaml
- Secret issues to be terminal conditions.
- Updated runtime
- New code with updated code generator
- Removed AutoMinorVersionUpgrade and NumCacheClusters
- Updated an error and error message to be terminal condition
```
Conditions:
Message:  kubernetes secret not found
Status:   True
Type:     ACK.Terminal
```
```
Conditions:
Message:    At least one node group should be present.
Status:     True
Type:       ACK.Terminal
Status:     True
```
> ElastiCache Fixes with new code generator

- README.md
- helm/Chart.yaml
- helm/crds/elasticache.services.k8s.aws_cacheparametergroups.yaml
- helm/crds/elasticache.services.k8s.aws_replicationgroups.yaml
- helm/crds/elasticache.services.k8s.aws_snapshots.yaml
- helm/crds/elasticache.services.k8s.aws_usergroups.yaml
- helm/crds/elasticache.services.k8s.aws_users.yaml
- helm/crds/services.k8s.aws_adoptedresources.yaml
- helm/templates/cluster-role-controller.yaml
- helm/templates/deployment.yaml
- helm/templates/metrics-service.yaml
- helm/templates/role-reader.yaml
- helm/templates/role-writer.yaml
- helm/values.yaml
Dev preview release of ACK ElastiCache Controller v0.0.4
* Support for User, UserGroup resources
* SecretReference type for ReplicationGroup auth token and User access fields
* Defect fixes
> Release artifacts for dev preview release v0.0.4

- apis/v1alpha1/ack-generate-metadata.yaml
- go.mod
- go.sum
- helm/templates/deployment.yaml
- helm/values.yaml
- pkg/resource/cache_parameter_group/manager.go
- pkg/resource/cache_parameter_group/resource.go
- pkg/resource/cache_parameter_group/sdk.go
- pkg/resource/cache_subnet_group/manager.go
- pkg/resource/cache_subnet_group/resource.go
- pkg/resource/cache_subnet_group/sdk.go
- pkg/resource/replication_group/manager.go
- pkg/resource/replication_group/resource.go
- pkg/resource/replication_group/sdk.go
- pkg/resource/snapshot/manager.go
- pkg/resource/snapshot/resource.go
- pkg/resource/snapshot/sdk.go
- pkg/resource/user/manager.go
- pkg/resource/user/resource.go
- pkg/resource/user/sdk.go
- pkg/resource/user_group/manager.go
- pkg/resource/user_group/resource.go
- pkg/resource/user_group/sdk.go
Includes support for node selector in Helm artifacts, simplification of
the onSuccess/onError resource manager methods and fixes for duplicated
log record fields.
By submitting this pull request, I confirm that my contribution is made
under the terms of the Apache 2.0 license.
>  bring in ACK runtime v0.13.2

- apis/v1alpha1/ack-generate-metadata.yaml
- apis/v1alpha1/generator.yaml
- generator.yaml
- helm/templates/metrics-service.yaml
- pkg/resource/replication_group/sdk.go
- test/e2e/tests/test_replicationgroup.py
This fixes the failing negative scenario where we attempt to create a replication group with a `primaryClusterID` of a node that doesn't exist. Removed the skip marker from the test as it passes locally.
> Add CacheClusterNotFound terminal code

- pkg/resource/replication_group/custom_update_api.go
- pkg/resource/replication_group/custom_update_api_test.go
When spec is updated to perform Scale up and Scale in
we would need to perform Scale up first followed by
Scale in.
Similarly when we perform Scale down and Scale out
we would need to perform Scale out first.
> Scale up/down and Scale in/out memory considerations

- apis/v1alpha1/ack-generate-metadata.yaml
- apis/v1alpha1/annotations.go
- apis/v1alpha1/generator.yaml
- generator.yaml
- helm/templates/deployment.yaml
- helm/values.yaml
- pkg/resource/replication_group/annotations.go
- pkg/resource/replication_group/custom_set_output.go
- pkg/resource/replication_group/delta.go
- pkg/resource/replication_group/delta_util.go
- test/e2e/service_bootstrap.py
- test/e2e/tests/test_replicationgroup.py
This was fixed by moving the population of `Status.LogDeliveryConfigurations` to execute after each of Create, Update, and Describe (instead of just Describe). See changes in `custom_set_output.go`.
This was causing the desired and latest state to infinitely swap. Solution: re-copy `LogDeliveryConfigurations` from `desired.Spec` to `latest.Spec` after the modify API response is merged in to ensure spec patching has no effect on this field. See changes in `custom_set_output.go`.
https://github.com/aws-controllers-k8s/code-generator/pull/201 was an alternate solution but we were recommended to avoid doing something like this.
Solution: added in a few lines in `filterDelta` to remove the diff if log delivery is disabled and the API response is `nil`.
By submitting this pull request, I …
> fixes to log delivery modification

- apis/v1alpha1/ack-generate-metadata.yaml
- apis/v1alpha1/generator.yaml
- generator.yaml
- pkg/resource/replication_group/delta.go
- pkg/resource/replication_group/delta_util.go
- test/e2e/tests/test_replicationgroup.py
Nice.
Properly retrieve the latest state for these 3 fields and compare them to the desired state. For each of these 3 spec fields, obtaining the corresponding latest state requires processing of a different `Status` field due to the structure of the `DescribeReplicationGroups` API response
> Fix delta comparison for auto failover, multi AZ, primary cluster ID

- olm/olmconfig.yaml
Signed-off-by: Adam D. Cornett <adc@redhat.com>
N/A
Adding in the missing `kinds` to the olm config file. This ensures that when the `bundle` is created via the release process that `operator-sdk` does not throw any `warnings`. This then allows the PR to the community repos to be raised without any issues since the community repos run `operator-sdk validate bundle` which may reject `warnings`.
> adding in missing kinds to olm config

- helm/Chart.yaml
- helm/templates/deployment.yaml
- helm/values.yaml
Release artifacts with latest bug fixes.
> Release artifacts for dev preview release v0.0.8

- apis/v1alpha1/ack-generate-metadata.yaml
- cmd/controller/main.go
- config/controller/kustomization.yaml
- helm/Chart.yaml
- helm/templates/NOTES.txt
- helm/values.yaml
Regenerated controller with latest runtime for release `v0.0.18`
> Release artifacts for release `v0.0.18`

- apis/v1alpha1/ack-generate-metadata.yaml
- apis/v1alpha1/generator.yaml
- generator.yaml
- pkg/resource/cache_subnet_group/sdk.go
- templates/hooks/cache_subnet_group/sdk_read_many_post_set_output.go.tpl
**Issue #, if available:** https://github.com/aws-controllers-k8s/community/issues/1725
**Description of changes:**
- Adding the subnetIDs after the custom describe operation in order to populate the `spec.subnetIDs` field.
> Add subnetIDs after custom describe to fix `spec.subnetIDs: Required value`

- pkg/resource/replication_group/delta_util.go
- pkg/resource/replication_group/delta_util_test.go
The purpose of this changes is to avoid the controller to compare patch versions when Redis version is >=6, since It's managed by AWS. More details [here](https://github.com/aws-controllers-k8s/community/issues/1737). 
> redis >=6 skip patch version compare

- apis/v1alpha1/ack-generate-metadata.yaml
- apis/v1alpha1/cache_subnet_group.go
- apis/v1alpha1/generator.yaml
- apis/v1alpha1/replication_group.go
- apis/v1alpha1/zz_generated.deepcopy.go
- cmd/controller/main.go
- config/crd/bases/elasticache.services.k8s.aws_cachesubnetgroups.yaml
- config/crd/bases/elasticache.services.k8s.aws_replicationgroups.yaml
- config/rbac/cluster-role-controller.yaml
- generator.yaml
- go.mod
- go.sum
- helm/crds/elasticache.services.k8s.aws_cachesubnetgroups.yaml
- helm/crds/elasticache.services.k8s.aws_replicationgroups.yaml
- helm/templates/cluster-role-controller.yaml
- helm/templates/deployment.yaml
- pkg/resource/cache_subnet_group/delta.go
- pkg/resource/cache_subnet_group/references.go
- pkg/resource/replication_group/delta.go
- pkg/resource/replication_group/references.go
Closes aws-controllers-k8s/community#1513
Closes aws-controllers-k8s/community#1860
The following fields have had refs support added:
- CacheSubnetGroup.SubnetIDs: ec2.Subnet.Status.SubnetID
- ReplicationGroup.CacheParameterGroupName: CacheParameterGroup.Spec.CacheParameterGroupName
- ReplicationGroup.CacheSubnetGroupName: CacheSubnetGroup.Spec.CacheSubnetGroupName
- ReplicationGroup.SecurityGroupIDs: ec2.SecurityGroup.Status.ID
---
> feat: add refs support for various fields

- pkg/resource/replication_group/post_set_output.go
This will set the value for the number of node groups of a ReplicationGroup to the value given in the Spec, thereby enabling horizontal scaling.
Fixes aws-controllers-k8s/community#2080.
> Fix horizontal scaling for ReplicationGroups

- apis/v1alpha1/ack-generate-metadata.yaml
- apis/v1alpha1/generator.yaml
- generator.yaml
- pkg/resource/cache_parameter_group/sdk.go
- pkg/resource/user/sdk.go
[aws-controllers-k8s/community#2387](https://github.com/aws-controllers-k8s/community/issues/2387)
Remove following Terminal Error codes:
`user.DefaultUserAssociatedToUserGroup`;
`cache_parameter_group.InvalidCacheParameterGroupState`.
> Update terminal err codes

- apis/v1alpha1/ack-generate-metadata.yaml
- helm/templates/deployment.yaml
- pkg/resource/replication_group/hooks.go
Fixes: https://github.com/aws-controllers-k8s/community/issues/2299
fixes the issue where in-place upgrades from ElastiCache Redis to Valkey clusters failed with `InvalidParameterCombination: valkey parameter group is not applicable to engine redis`. The problem occurred because the ElastiCache controller's custom `ModifyReplicationGroup` implementation was missing the `Engine` and `CacheParameterGroupName` fields in the API request payload, causing AWS to reject Valkey parameter groups being applied to what it perceived as a Redis engine. Additionally, the `ModifyReplicationGroup` API returns stale field values that don't immediately reflect requested changes, leading the controller to detect false differences and trigger terminal conditions. The solution adds …
> Fix Redis to Valkey in-place upgrade by handling Engine in ModifyReplicationGroup
